name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: |
          go get .
      #    go install github.com/vladopajic/go-test-coverage/v2@latest
      - name: Test with Go
        run: go test ./... -cover -v
      # - name: Test with Go and go-test-coverage
      #   run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      # - name: Check test coverage
      #   uses: vladopajic/go-test-coverage@v2
      #   with:
      #     config: ./.github/test-coverage.yml
